
export enum IncidentCode {
    REQUEST_ERROR = "REQUEST_ERROR",
    REQUEST_ERROR_UNAUTHORIZED = "REQUEST_ERROR_UNAUTHORIZED",
    DEFAULT_TOKEN = "DEFAULT_TOKEN",
    TOKEN_SET = "TOKEN_SET",
    TOKEN_CLEARED = "TOKEN_CLEARED",
    TOKEN_INVALIDATED = "TOKEN_INVALIDATED",
    PRE_FAILED_CALL = "PRE_FAILED_CALL",
    RETRY_LIMIT_REACHED = "RETRY_LIMIT_REACHED",
    NEW_TOKEN_SUBSCRIBER = "Subscription to token updates",
    NEW_INCIDENT_REGISTRED = "NEW_INCIDENR_REGISTRED",
    REQUESTED_TOKEN_FROM_COOKIES = "REQUESTING_TOKEN_FROM_COOKIES",
    RESPONSE_UNDEFINED= "RESPONSE_UNDEFINED",
    RESPONSE_DESERIALIZATION_ERROR= "RESPONSE_DESERIALIZATION_ERROR"
}