export enum RequestError {
    NONE = 0,
    OTHER = 1000,
    SERVER_UNAUTHORIZED = 401,
    SERVER_TOO_MANY_REQUESTS = 429,
    SERVER_INTERNAL_SERVER_ERROR = 500,
    
    DATA_RESPONSE_UNDEFINED = 1001,
   
}