export enum AuthEvent {
    TOKEN_SET = "TOKEN_SET",
    TOKEN_CLEARED = "TOKEN_CLEARED",
    TOKEN_INVALIDATED = "TOKEN_INVALIDATED",
    PRE_FAILED_CALL = "PRE_FAILED_CALL",
    RETRY_LIMIT_REACHED = "RETRY_LIMIT_REACHED",
}